name: 'ZDT Checkout'
description: 'Custom action to checkout a git repository'
runs:
  using: 'composite'
  steps:
  - run: git clone https://github.com/${{ github.repository }} ${{ github.workspace }}
    shell: bash
